export const USERS = [
  {
    id: 1,
    username: 'user1',
    password: 'password1',
    gender: 'male',
    age: 20,
    firstName: 'John',
    lastName: 'Doe',
  },
  {
    id: 2,
    username: 'user2',
    password: 'password2',
    gender: 'female',
    age: 25,
    firstName: 'Jane',
    lastName: 'Smith',
  },
  {
    id: 3,
    username: 'user3',
    password: 'password3',
    gender: 'male',
    age: 30,
    firstName: 'Bob',
    lastName: 'Johnson',
  },
  {
    id: 4,
    username: 'user4',
    password: 'password4',
    gender: 'female',
    age: 35,
    firstName: 'Alice',
    lastName: 'Williams',
  },
  {
    id: 5,
    username: 'user5',
    password: 'password5',
    gender: 'male',
    age: 40,
    firstName: 'Charlie',
    lastName: 'Brown',
  },
  {
    id: 6,
    username: 'user6',
    password: 'password6',
    gender: 'female',
    age: 45,
    firstName: 'Eve',
    lastName: 'Jones',
  },
];