export const SEARCHPOSTS = [
  {
    id: 1,
    image: "https://i.pinimg.com/1200x/aa/40/56/aa405686c70a4fb40b90bf66cdff16bc.jpg",
    text: "фыв",
    date: "2021-10-06",
    lesson_num: 123,
    title: "What's Really Out There: Your Guide to Space",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 2,
    image: "https://i.pinimg.com/1200x/49/a5/33/49a533f8e2c8f4332df2b5c5eb7c91c9.jpg",
    text: "фыв",
    date: "2021-02-11",
    lesson_num: 123,
    title: "Is There Life on Other Planets",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 3,
    image: "https://i.pinimg.com/1200x/eb/7b/63/eb7b63bae2785561eb4acca6429e20b5.jpg",
    text: "фыв",
    date: "2021-12-22",
    lesson_num: 123,
    title: "How Big is the Universe Really",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 4,
    image: "https://i.pinimg.com/1200x/4d/f5/eb/4df5ebbb11c25d24a5b597300ddf7ba5.jpg",
    text: "фыв",
    date: "2021-06-06",
    lesson_num: 123,
    title: "Will We Ever Travel to Other Stars",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 5,
    image: "https://i.pinimg.com/1200x/65/d0/84/65d0847eb3d655e8dcaac4fed59c6481.jpg",
    text: "фыв",
    date: "2021-09-01",
    lesson_num: 123,
    title: "What Happens When You Go to Space",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 6,
    image: "https://i.pinimg.com/1200x/fe/47/b4/fe47b499b43eab897ad85e5c6b6ec0e9.jpg",
    text: "фыв",
    date: "2021-01-09",
    lesson_num: 123,
    title: "What Are Black Holes and How Do They Work",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 7,
    image: "https://i.pinimg.com/736x/be/9a/d8/be9ad82af7bc33466686a00171a1b3d2.jpg",
    text: "фыв",
    date: "2021-12-12",
    lesson_num: 123,
    title: "Can We Live on Mars Someday",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 8,
    image: "https://i.pinimg.com/1200x/63/93/03/639303acfcb016e4545b3a1dccec700c.jpg",
    text: "фыв",
    date: "2020-17-16",
    lesson_num: 123,
    title: "How Are New Planets Discovered",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  },
  {
    id: 9,
    image: "https://i.pinimg.com/1200x/03/74/c6/0374c6a444ac3627a4c763449a37582b.jpg",
    text: "фыв",
    date: "2022-11-06",
    lesson_num: 123,
    title: "Could Aliens Visit Us Someday",
    description: "default default default default default default default default default default default default default default default default default default default default default default default default default default default",
    author: 7,
  }
]